#!/usr/bin/php
<?php

use Symfony\Component\Console\Application;
use Graphiter\Command\MonitorCommand;

require_once __DIR__ . '/../vendor/autoload.php';

$application = new Application();
$application->add(new MonitorCommand());
$application->run();
